### ISSUE TITLE
negative prompt pop-up bug

### ISSUE THREAD

**Issue by harukaxxxx** [hyd998877/stable-diffusion-webui-auto-translate-language#2]
The negative prompt pop-up does not correctly input text into the negative prompt text box.
Here are the steps to reproduce the issue:

1. Click the 'N2' button.
2. Type the text into the pop-up.
3. Click 'Translate'.
4. The translated text appears in the prompt text box instead of the Negative Prompt text box.

**Comment by hyd998877** [comment]
the bug is fix,please update
