### ISSUE TITLE
requirements.txt Conflict

### ISSUE THREAD

**Issue by longgui0318** [hyd998877/stable-diffusion-webui-auto-translate-language#9]
googletrans use httpx 0.13.3。but stable-diffusion-webui need hgher versions.

After this plugin is installed, it will cause a series of network errors, such as Error on the interface, and the generated images will not be displayed back on the interface.

googletrans==4.0.0rc1
  - httpx [required: ==0.13.3, installed: 0.13.3]
    - certifi [required: Any, installed: 2022.12.7]
    - chardet [required: ==3.*, installed: 3.0.4]
    - hstspreload [required: Any, installed: 2023.1.1]
    - httpcore [required: ==0.9.*, installed: 0.9.1]
      - h11 [required: >=0.8,<0.10, installed: 0.9.0]
      - h2 [required: ==3.*, installed: 3.2.0]
        - hpack [required: >=3.0,<4, installed: 3.0.0]
        - hyperframe [required: >=5.2.0,<6, installed: 5.2.0]
      - sniffio [required: ==1.*, installed: 1.3.0]
    - idna [required: ==2.*, installed: 2.10]
    - rfc3986 [required: >=1.3,<2, installed: 1.5.0]
    - sniffio [required: Any, installed: 1.3.0]

**Comment by hyd998877** [comment]
translators is a stable library, now remove googletrans==4.0.0rc1
